=== molejar/embsysregview/trunk/org.eclipse.cdt.embsysregview/data/cortex-m4/TexasInstruments/embsysregview.dtd
<!ELEMENT model (chip_description?,boards?,group*)>
<!ATTLIST model chipname CDATA #REQUIRED>

<!ELEMENT chip_description (#PCDATA)>

<!ELEMENT boards (board*)>

<!ELEMENT board EMPTY>
<!ATTLIST board id CDATA #REQUIRED>
<!ATTLIST board name CDATA #REQUIRED>
<!ATTLIST board designer CDATA #IMPLIED>

<!ELEMENT group (registergroup*)>
<!ATTLIST group name CDATA #REQUIRED>
<!ATTLIST group description CDATA #IMPLIED>

<!ELEMENT registergroup (register*)>
<!ATTLIST registergroup name CDATA #REQUIRED>
<!ATTLIST registergroup description CDATA #IMPLIED>

<!ELEMENT register (description?,field*)>
<!ATTLIST register name CDATA #REQUIRED>
<!ATTLIST register description CDATA #IMPLIED>
<!ATTLIST register address CDATA #REQUIRED>
<!ATTLIST register resetvalue CDATA #IMPLIED>
<!ATTLIST register access CDATA #IMPLIED>
<!ATTLIST register size CDATA #IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT field (description?,interpretation*)>
<!ATTLIST field board_id CDATA #IMPLIED>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field description CDATA #IMPLIED>
<!ATTLIST field bitoffset CDATA #REQUIRED>
<!ATTLIST field bitlength CDATA #REQUIRED>

<!ELEMENT interpretation EMPTY>
<!ATTLIST interpretation key CDATA #REQUIRED>
<!ATTLIST interpretation text CDATA #REQUIRED>

=== molejar/embsysregview/trunk/org.eclipse.cdt.embsysregview.data/data/cortex-m3/TexasInstruments/lm3s2276.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "embsysregview.dtd">

<model chipname="LM3S2276">
  <chip_description>CPU                               ARM Cortex M3
Max Speed (MHz)                   50
SRAM (kB)                         32
Motion PWM                        8
QEI                               0
GPIOs                             33
Operating Temperature Range (C)   -40 to 85
USB D, H/D, or OTG                No
SSI/SPI                           1
I2C                               1
UART                              1
ADC Channels                      6
ADC Resolution (Bits)             10
SysTick                           Yes
Watchdog Timers                   1
EPI/EMIF                          No
Ethernet (10/100 MAC+PHY)         No
10/100 MAC with MII Interface     No
I2S                               No
RTC                               Yes
ADC Units                         1
Maximum 5-V Tolerant GPIOs        33
ADC Sample Rate (kSPS)            1000
ROM Software Libraries            Yes
Battery-Backed Hibernation Module Yes
Internal Temp Sensor              1
Internal LDO Voltage Regulator    Yes
Memory Protection Unit (MPU)      Yes
UART Modem Signalling             0
Analog Comparators                0
Digital Comparators               0
IEEE 1588                         No
Boot Loader in ROM                1
CAN MAC                           1
16 MHz Precision Oscillators      No
Capture Pins                      1
Timers                            4
ADC Ext Reference                 No
Interrupts (Count)                30
Pin/Package                       64LQFP
Flash (KB)                        64
Sample &amp; Buy


Copyright Texas Instruments Incorporated. All rights reserved.</chip_description>
  <group name="WATCHDOG" description="Watchdog Timer registers">
    <registergroup name="WATCHDOG0" description="">
      <register name="WATCHDOG0_LOAD_R" description="" address="0x40000000" access="rw" />
      <register name="WATCHDOG0_VALUE_R" description="" address="0x40000004" access="rw" />
      <register name="WATCHDOG0_CTL_R" description="" address="0x40000008" access="rw" />
      <register name="WATCHDOG0_ICR_R" description="" address="0x4000000C" access="rw" />
      <register name="WATCHDOG0_RIS_R" description="" address="0x40000010" access="rw" />
      <register name="WATCHDOG0_MIS_R" description="" address="0x40000014" access="rw" />
      <register name="WATCHDOG0_TEST_R" description="" address="0x40000418" access="rw" />
      <register name="WATCHDOG0_LOCK_R" description="" address="0x40000C00" access="rw" />
    </registergroup>
    <registergroup name="NVIC" description="">
      <register name="WATCHDOG_LOAD_R" description="" address="0x40000000" access="rw" />
      <register name="WATCHDOG_VALUE_R" description="" address="0x40000004" access="rw" />
      <register name="WATCHDOG_CTL_R" description="" address="0x40000008" access="rw" />
      <register name="WATCHDOG_ICR_R" description="" address="0x4000000C" access="rw" />
      <register name="WATCHDOG_RIS_R" description="" address="0x40000010" access="rw" />
      <register name="WATCHDOG_MIS_R" description="" address="0x40000014" access="rw" />
      <register name="WATCHDOG_TEST_R" description="" address="0x40000418" access="rw" />
      <register name="WATCHDOG_LOCK_R" description="" address="0x40000C00" access="rw" />
    </registergroup>
  </group>
  <group name="GPIO" description="GPIO registers">
    <registergroup name="PORTA" description="">
      <register name="GPIO_PORTA_DATA_BITS_R" description="" address="0x40004000" access="rw" />
      <register name="GPIO_PORTA_DATA_R" description="" address="0x400043FC" access="rw" />
      <register name="GPIO_PORTA_DIR_R" description="" address="0x40004400" access="rw" />
      <register name="GPIO_PORTA_IS_R" description="" address="0x40004404" access="rw" />
      <register name="GPIO_PORTA_IBE_R" description="" address="0x40004408" access="rw" />
      <register name="GPIO_PORTA_IEV_R" description="" address="0x4000440C" access="rw" />
      <register name="GPIO_PORTA_IM_R" description="" address="0x40004410" access="rw" />
      <register name="GPIO_PORTA_RIS_R" description="" address="0x40004414" access="rw" />
      <register name="GPIO_PORTA_MIS_R" description="" address="0x40004418" access="rw" />
      <register name="GPIO_PORTA_ICR_R" description="" address="0x4000441C" access="rw" />
      <register name="GPIO_PORTA_AFSEL_R" description="" address="0x40004420" access="rw" />
      <register name="GPIO_PORTA_DR2R_R" description="" address="0x40004500" access="rw" />
      <register name="GPIO_PORTA_DR4R_R" description="" address="0x40004504" access="rw" />
      <register name="GPIO_PORTA_DR8R_R" description="" address="0x40004508" access="rw" />
      <register name="GPIO_PORTA_ODR_R" description="" address="0x4000450C" access="rw" />
      <register name="GPIO_PORTA_PUR_R" description="" address="0x40004510" access="rw" />
      <register name="GPIO_PORTA_PDR_R" description="" address="0x40004514" access="rw" />
      <register name="GPIO_PORTA_SLR_R" description="" address="0x40004518" access="rw" />
      <register name="GPIO_PORTA_DEN_R" description="" address="0x4000451C" access="rw" />
      <register name="GPIO_PORTA_LOCK_R" description="" address="0x40004520" access="rw" />
      <register name="GPIO_PORTA_CR_R" description="" address="0x40004524" access="rw" />
      <register name="GPIO_PORTA_AMSEL_R" description="" address="0x40004528" access="rw" />
    </registergroup>
    <registergroup name="PORTB" description="">
      <register name="GPIO_PORTB_DATA_BITS_R" description="" address="0x40005000" access="rw" />
      <register name="GPIO_PORTB_DATA_R" description="" address="0x400053FC" access="rw" />
      <register name="GPIO_PORTB_DIR_R" description="" address="0x40005400" access="rw" />
      <register name="GPIO_PORTB_IS_R" description="" address="0x40005404" access="rw" />
      <register name="GPIO_PORTB_IBE_R" description="" address="0x40005408" access="rw" />
      <register name="GPIO_PORTB_IEV_R" description="" address="0x4000540C" access="rw" />
      <register name="GPIO_PORTB_IM_R" description="" address="0x40005410" access="rw" />
      <register name="GPIO_PORTB_RIS_R" description="" address="0x40005414" access="rw" />
      <register name="GPIO_PORTB_MIS_R" description="" address="0x40005418" access="rw" />
      <register name="GPIO_PORTB_ICR_R" description="" address="0x4000541C" access="rw" />
      <register name="GPIO_PORTB_AFSEL_R" description="" address="0x40005420" access="rw" />
      <register name="GPIO_PORTB_DR2R_R" description="" address="0x40005500" access="rw" />
      <register name="GPIO_PORTB_DR4R_R" description="" address="0x40005504" access="rw" />
      <register name="GPIO_PORTB_DR8R_R" description="" address="0x40005508" access="rw" />
      <register name="GPIO_PORTB_ODR_R" description="" address="0x4000550C" access="rw" />
      <register name="GPIO_PORTB_PUR_R" description="" address="0x40005510" access="rw" />
      <register name="GPIO_PORTB_PDR_R" description="" address="0x40005514" access="rw" />
      <register name="GPIO_PORTB_SLR_R" description="" address="0x40005518" access="rw" />
      <register name="GPIO_PORTB_DEN_R" description="" address="0x4000551C" access="rw" />
      <register name="GPIO_PORTB_LOCK_R" description="" address="0x40005520" access="rw" />
      <register name="GPIO_PORTB_CR_R" description="" address="0x40005524" access="rw" />
      <register name="GPIO_PORTB_AMSEL_R" description="" address="0x40005528" access="rw" />
    </registergroup>
    <registergroup name="PORTC" description="">
      <register name="GPIO_PORTC_DATA_BITS_R" description="" address="0x40006000" access="rw" />
      <register name="GPIO_PORTC_DATA_R" description="" address="0x400063FC" access="rw" />
      <register name="GPIO_PORTC_DIR_R" description="" address="0x40006400" access="rw" />
      <register name="GPIO_PORTC_IS_R" description="" address="0x40006404" access="rw" />
      <register name="GPIO_PORTC_IBE_R" description="" address="0x40006408" access="rw" />
      <register name="GPIO_PORTC_IEV_R" description="" address="0x4000640C" access="rw" />
      <register name="GPIO_PORTC_IM_R" description="" address="0x40006410" access="rw" />
      <register name="GPIO_PORTC_RIS_R" description="" address="0x40006414" access="rw" />
      <register name="GPIO_PORTC_MIS_R" description="" address="0x40006418" access="rw" />
      <register name="GPIO_PORTC_ICR_R" description="" address="0x4000641C" access="rw" />
      <register name="GPIO_PORTC_AFSEL_R" description="" address="0x40006420" access="rw" />
      <register name="GPIO_PORTC_DR2R_R" description="" address="0x40006500" access="rw" />
      <register name="GPIO_PORTC_DR4R_R" description="" address="0x40006504" access="rw" />
      <register name="GPIO_PORTC_DR8R_R" description="" address="0x40006508" access="rw" />
      <register name="GPIO_PORTC_ODR_R" description="" address="0x4000650C" access="rw" />
      <register name="GPIO_PORTC_PUR_R" description="" address="0x40006510" access="rw" />
      <register name="GPIO_PORTC_PDR_R" description="" address="0x40006514" access="rw" />
      <register name="GPIO_PORTC_SLR_R" description="" address="0x40006518" access="rw" />
      <register name="GPIO_PORTC_DEN_R" description="" address="0x4000651C" access="rw" />
      <register name="GPIO_PORTC_LOCK_R" description="" address="0x40006520" access="rw" />
      <register name="GPIO_PORTC_CR_R" description="" address="0x40006524" access="rw" />
      <register name="GPIO_PORTC_AMSEL_R" description="" address="0x40006528" access="rw" />
    </registergroup>
    <registergroup name="PORTD" description="">
